[[repositories]]
path = "."
prefix = ""
repos = [
  "git@github.com:mirrorboards/.vscode.git",
]

# .legacy
# [[repositories]]
# path = ".legacy"
# prefix = ""
# repos = [
#   "git@github.com:mirrorboards/mirrorboards-next-next.git",
#   "git@github.com:mirrorboards/mirrorboards-dev.git",
#   "git@github.com:mirrorboards/mirrorboards-next.git",
#   "git@github.com:mirrorboards/mirrorboards-dev2.git",
#   "git@github.com:mirrorboards/mirrorboards-legacy.git",
# ]

# mirrorboards
[[repositories]]
path = "mirrorboards"
prefix = ""
repos = [
  "git@github.com:mirrorboards/mirrorboards-install.git",
  "git@github.com:mirrorboards/mirrorboards-fish-functions.git",
  "git@github.com:mirrorboards/mirrorboards-go.git",
]

[[repositories]]
path = "."
prefix = "mirrorboards"
repos = [
  "git@github.com:mirrorboards/platform.git",
]

# # pay2vault
[[repositories]]
path = "."
prefix = ""
repos = [
  "git@github.com:pay2vault/pay2vault-platform.git",
]

[[repositories]]
path = "pay2vault"
prefix = ""
repos = [
  "git@github.com:pay2vault/pay2vault.git",
]

[[repositories]]
path = "exchange"
prefix = ""
repos = [
  "git@github.com:mirrorboards-exchange/mirrorboards-exchange-operations.git",
  "git@github.com:mirrorboards-exchange/mirrorboards-exchange-platform.git",
]

[[repositories]]
path = "xauth-net"
prefix = ""
repos = [
  "git@github.com:xauth-net/xauth-net-platform.git",
]
