[[repositories]]
path = "."
prefix = ""
repos = [
  "git@github.com:mirrorboards/.vscode.git",
]

# .legacy
# [[repositories]]
# path = ".legacy"
# prefix = ""
# repos = [
#   "git@github.com:mirrorboards/mirrorboards-next-next.git",
#   "git@github.com:mirrorboards/mirrorboards-dev.git",
#   "git@github.com:mirrorboards/mirrorboards-next.git",
#   "git@github.com:mirrorboards/mirrorboards-dev2.git",
#   "git@github.com:mirrorboards/mirrorboards-legacy.git",
# ]

# mirrorboards
[[repositories]]
path = "mirrorboards"
prefix = ""
repos = [
  "git@github.com:mirrorboards/mirrorboards-install.git",
  "git@github.com:mirrorboards/mirrorboards-fish-functions.git",
]

# [[repositories]]
# path = "mirrorboards"
# prefix = "mirrorboards-utils"
# repos = [
#   "git@github.com:mirrorboards/init.git",
#   "git@github.com:mirrorboards/fish.git",
# ]

# [[repositories]]
# path = "."
# prefix = "mirrorboards"
# repos = [
#   "git@github.com:mirrorboards/platform.git",
# ]

# # pay2vault
# [[repositories]]
# path = "."
# prefix = ""
# repos = [
#   "git@github.com:mirrorboards/pay2vault-platform.git",
# ]

# [[repositories]]
# path = "pay2vault"
# prefix = ""
# repos = [
#   "git@github.com:mirrorboards/pay2vault.git",
# ]

# [[repositories]]
# path = "."
# prefix = ""
# repos = [
#   "git@github.com:mirrorboards/pay2vault-platform.git",
# ]

# # exchange
# [[repositories]]
# path = "exchange"
# prefix = "exchange"
# repos = [
#   "git@github.com:mirrorboards-exchange/operations.git",
# ]

# # exchange
# [[repositories]]
# path = "."
# prefix = "exchange"
# repos = [
#   "git@github.com:mirrorboards-exchange/platform.git",
# ]

# # xauth-platform
# [[repositories]]
# path = "."
# prefix = ""
# repos = [
#   "git@github.com:mirrorboards/xauth-platform.git",
# ]
