[[repositories]]
path = "."
repos = [
  {remote = "git@github.com:mirrorboards/mirrorboards-vscode.git", dest = ".vscode"},
]

[[repositories]]
path = "."
repos = [
  {remote = "git@github.com:mirrorboards/mirrorboards-legacy.git", dest = ".legacy"},
]

[[repositories]]
path = "."
repos = [
  {remote = "git@github.com:mirrorboards/mirrorboards-bin.git", dest = "bin"},
]

[[repositories]]
path = "exchange"
repos = [
  {remote = "git@github.com:mirrorboards-exchange/mirrorboards-exchange-operations.git", dest = "exchange-operations"},
]

[[repositories]]
path = "."
repos = [
  {remote = "git@github.com:mirrorboards-exchange/mirrorboards-exchange-platform.git", dest = "exchange-platform"},
]

[[repositories]]
path = "mirrorboards"
repos = [
  {remote = "git@github.com:mirrorboards/mirrorboards.git", dest = "mirrorboards"},
  {remote = "git@github.com:mirrorboards/mirrorboards-go.git", dest = "mirrorboards-go"},
]

[[repositories]]
path = "mirrorboards-utils"
repos = [
  {remote = "git@github.com:mirrorboards/mirrorboards-install.git", dest = "mirrorboards-install"},
  {remote = "git@github.com:mirrorboards/mirrorboards-fish-functions.git", dest = "mirrorboards-fish-functions"},
]

[[repositories]]
path = "."
repos = [
  {remote = "git@github.com:mirrorboards/platform.git", dest = "mirrorboards-platform"},
]

[[repositories]]
path = "pay2vault"
repos = [
  {remote = "git@github.com:pay2vault/pay2vault-api.git", dest = "pay2vault-api"},
  {remote = "git@github.com:pay2vault/pay2vault-mobile.git", dest = "pay2vault-mobile"},
  {remote = "git@github.com:pay2vault/pay2vault-web.git", dest = "pay2vault-web"},
]

[[repositories]]
path = "."
repos = [
  {remote = "git@github.com:pay2vault/pay2vault-platform.git", dest = "pay2vault-platform"},
]

[[repositories]]
path = "."
repos = [
  {remote = "git@github.com:xauth-net/xauth-net-platform.git", dest = "xauth-net-platform"},
]

# #   "git@github.com:mirrorboards/mirrorboards-next-next.git",
# #   "git@github.com:mirrorboards/mirrorboards-dev.git",
# #   "git@github.com:mirrorboards/mirrorboards-next.git",
# #   "git@github.com:mirrorboards/mirrorboards-dev2.git",
# #   "git@github.com:mirrorboards/mirrorboards-legacy.git",
